trigger:
  branches:
    include:
      - master

stages:
- stage: versioning
  displayName: Versioning
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: gitversion
    displayName: GitVersion
    steps:
      # Requires https://marketplace.visualstudio.com/items?itemName=gittools.gittools
      - task: gitversion/setup@0
        displayName: Install GitVersion
        inputs:
          versionSpec: '5.x'

      - task: gitversion/execute@0
        displayName: Determine Version
        inputs:
          useConfigFile: true
          configFilePath: gitversion.yml

      - task: PowerShell@2
        displayName: Set buildnumber
        name: setbuildnumber
        inputs:
          targetType: inline
          script: write-host "##vso[build.updatebuildnumber]$(FullSemVer)"

- stage: build
  displayName: Build and publish
  dependsOn: versioning
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: package
    displayName: Package
    steps:
      - task: CmdLine@2
        displayName: Install tools
        inputs:
          script: |
            pip install wheel
            pip install twine
            pip install --upgrade requests

      - task: TwineAuthenticate@1
        inputs:
          artifactFeed: Python
      
      - task: CmdLine@2
        displayName: Build wheel
        inputs:
          script: |
            python setup.py clean --all sdist bdist_wheel

      - task: CmdLine@2
        displayName: Publish package
        inputs:
          script: twine upload -r Python dist/* --non-interactive --repository-url https://pkgs.dev.azure.com/CallOfTheVoid/_packaging/Python/pypi/upload/