trigger:
  branches:
    include:
      - master

stages:
- stage: build
  displayName: Build and publish
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: package
    displayName: Package
    steps:
      - task: CmdLine@2
        displayName: Build wheel
        inputs:
          script: |
            python setup.py clean --all sdist bdist_wheel

      - task: CmdLine@2
        displayName: List items
        inputs:
          script: |
            ls -la dist